### ISSUE TITLE
enhancement: Module tab

### ISSUE THREAD

**Issue by Nicola1971** [pmfx/ElementsInTree#1]
thinking about a possible addditional tab.

Revo has the "files" tab, should be nice, but I think that Evo need more a Module tab.

I know we have not much space , but the module section is very critical when you have a lot of modules. 

I think a lot of people will appreciate it

**Comment by pmfx** [comment]
Haven't thought about it before. I like it :) 
We could squeeze it easily by having a slightly smaller horizontal tab padding.

**Comment by Nicola1971** [comment]
done

![wdu6dbomt5z8gaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/7342798/19416780/9e9289a8-9399-11e6-9619-8e1e57d6ae3a.png)

**Comment by pmfx** [comment]
Great! Tested it but I think it should run module instead of editing it on click. Right? And should we have cogs icons in <li> like we have in other tabs?

**Comment by Nicola1971** [comment]
just added icons.

you are right better run the module

**Comment by Nicola1971** [comment]
changed to run module

**Comment by Nicola1971** [comment]
![vwjsndh5bhuaaaaasuvork5cyii](https://cloud.githubusercontent.com/assets/7342798/19416918/405280d2-939e-11e6-97c7-ff53fcf8bed6.png)

**Comment by pmfx** [comment]
Great!
Two more things spotted.

Line 276: 
after
 **|| $modx->hasPermission('edit_plugin')**
add 
 **|| $modx->hasPermission('exec_module')**

Line 350:
Replace
**edit_module**
with
**exec_module**

**Comment by Nicola1971** [comment]
thanks, fixed permissions

**Comment by pmfx** [comment]
Now it's perfect, thanks!
