### ISSUE TITLE
No TV's visible

### ISSUE THREAD

**Issue by fourroses666** [pmfx/ElementsInTree#19]
https://github.com/modxcms/evolution/issues/888#issuecomment-258795182

**Comment by pmfx** [comment]
Is "Content" category actually empty? Have you tried clicking on it or on the search input? Sometimes "arrow" icon can be misleading.

**Comment by fourroses666** [comment]
Must check tonight

**Comment by fourroses666** [comment]
Hmm just checked, it does work.

by default its not folded which should folded be right? Anyway I will close this

**Comment by Deesen** [comment]
I tested also again. You can delete the localStorage-item which is keeping the values of open/closed categories. In Firefox you can open JS-console (STRG-Shift-I -> last tab) and use this command to delete the item: `localStorage.removeItem("MODX_elementsInTreeParams");`

I deleted it, so it is like a fresh MODX-installation. I reloaded manager and all categories were open by default so not sure what happened on your side. Just mentioning.

**Comment by fourroses666** [comment]
Does local storage also remember the setting in an other browser?
I tested in an other browser, it was not folded by default.

Also the arrows are misleading. I was expecting it was folded and didn't see any TVs.
After clicking the showed up.
They need to be down when its folded and sideways when not I think.

![folded](https://cloud.githubusercontent.com/assets/523389/20170563/2061ed24-a72d-11e6-8e27-eac57fd8cac3.jpg)
![not-folded](https://cloud.githubusercontent.com/assets/523389/20170562/20602cfa-a72d-11e6-927e-1235c9e8bb38.jpg)

**Comment by pmfx** [comment]
Same for me. Sometimes arrows act weird. Mostly for last category on list or if there is only one category. Same for other elements (chunks, snippets...).

**Comment by fourroses666** [comment]
Ah yea, when adding another one its ok.

**Comment by Deesen** [comment]
@fourroses666 No localStorage is locally saved in your browser and per domain. And "another one" what? Category or snippet etc?

**Comment by Deesen** [comment]
And: Are you really always using latest version?

**Comment by fourroses666** [comment]
_(Mine is from yesterday. Latest develop)_
You don't have these arrows mixed up when only having 1 item in a category?
When I add another TV and having two items the arrows are correct again.

**Comment by Deesen** [comment]
No. I just added a new TV in a new category and saved. elementsTree updated automatically with the new category opened like:

![eltree](https://cloud.githubusercontent.com/assets/8569221/20172803/cfa7bf4e-a736-11e6-95a9-1bfae0b5a41f.png)

**Comment by Deesen** [comment]
Maybe it is a Chrome / Firefox-thingy again.....?

**Comment by fourroses666** [comment]
Only when there is 1 item (and 1 category). When I have 2 TVs and 2 categorys its ok.

**Comment by fourroses666** [comment]
Argh, very weird, can't reproduce it anymore even after deleting all TVs.

**Comment by Deesen** [comment]
I can only expain it to myself when you installed new version on a domain where you already used old version. So old localStorage-object is used by new script or so.

**Comment by fourroses666** [comment]
Going to close this issue, will have a look on a new install this weekend if I can reproduce ( and if my new router will be delivered and works :( ).

**Comment by fourroses666** [comment]
New install, cleared local storage, have only 1 chunk, then the aroow isn't correct.
After clicking once on the category it folds and the localstorage is saved.
But the arrow isn't correct.
![x](https://cloud.githubusercontent.com/assets/523389/20237551/15147f36-a8d6-11e6-8d12-7eff86e5aaff.jpg)

But its not that important!

**Comment by Deesen** [comment]
Thanks for the detailed info, I finally found the reason & solution.

**Comment by fourroses666** [comment]
ok cool. :)
