### ISSUE TITLE
Auto refresh list when saving/deleting Element

### ISSUE THREAD

**Issue by pmfx** [pmfx/ElementsInTree#2]
Not sure yet if it is possible or how difficult it would be, but it would be good to have it.

**Comment by Deesen** [comment]
Can be solved by modxapi.ajax in future. Will also be needed for ajaxifying new features like https://github.com/modxcms/evolution/issues/822

**Comment by Deesen** [comment]
I was thinking too much about the API last week I guess. It could be solved by the plugin itself :

- using event "OnManagerMainFrameHeaderHTMLBlock"
- for adding a call to top.tree.location.reload() on form-submit

**Comment by pmfx** [comment]
Cool. Maybe better use Elements-specific events like:

- OnChunkFormSave
- OnChunkFormDelete
- OnModFormDelete
- OnModFormSave
- OnPluginFormSave
- OnPluginFormDelete
- OnSnipFormSave
- OnSnipFormDelete

Because OnManagerMainFrameHeaderHTMLBlock will reload sidebar everytime main frame reloads, right?

**Comment by Deesen** [comment]
Well no we need to inject Javascript, those events are for PHP. So in plugin checking for a-parameter in link it looks like

    if ( $e->name == "OnManagerMainFrameHeaderHTMLBlock" ) {
	  $relevantActions = array(16,301,78,22,102,108,76,106);
	  if(in_array($_GET['a'],$relevantActions)) {
           $output = '...';
           $e->output($output );
      }
    }

**Comment by Deesen** [comment]
It already works but I need to remove the animation of tree when collapsing categories automatically.. otherwise it could make some users nervous LOL..

**Comment by pmfx** [comment]
Ah OK, cool Deesen :D

**Comment by pmfx** [comment]
Works like a charm. I've removed "jumping" when buttons are moved to tab.

**Comment by pmfx** [comment]
Hm, but should it reload when opening Element?

**Comment by Deesen** [comment]
Needs some extensive testing ;-)..

**Comment by pmfx** [comment]
Almost there. Sometimes it doesn't work when duplicating Element.

**Comment by pmfx** [comment]
And my "jumping fix" should stay ;)

![2016-10-30-11-10-22](https://cloud.githubusercontent.com/assets/10888055/19835875/8b48989e-9e91-11e6-94b8-c693be3da1c6.png)

**Comment by pmfx** [comment]
Looking at actionlist.inc.php maybe those actions will be ok?

'20'	=> 'Saving template',
'302'	=> 'Save Template Variable',
'79'	=> 'Saving Chunk (HTML Snippet)',
'24'	=> 'Saving Snippet',
'103'	=> 'Saving plugin',
'109'	=> 'Saving module',

'21'	=> 'Deleting template',
'303'	=> 'Delete Template Variable',
'80'	=> 'Deleting Chunk (HTML Snippet)',
'25'	=> 'Deleting Snippet',
'104'	=> 'Delete plugin',
'110'	=> 'Delete module',

'96'	=> 'Duplicate Template',
'304'	=> 'Duplicate Template Variable',
'97'	=> 'Duplicate Chunk (HTML Snippet)',
'98'	=> 'Duplicate Snippet',
'105'	=> 'Duplicate plugin',
'111'	=> 'Duplicate module'

**Comment by Deesen** [comment]
Sry, was no intention with "jump-fix".. reg. action-list, no it makes no sense to use the duplicate action-ids because no plugin will get invoked in these actions.

**Comment by Deesen** [comment]
Reg. "sometimes doesnt work".. can you find out in which cases it doesn´t work?

**Comment by Deesen** [comment]
Sorry, just a logical mistake..

**Comment by pmfx** [comment]
Almost there, again ;) Don't work when clicking "Save + Add another".

**Comment by pmfx** [comment]
But this will probably turn on reloading on opening Element, right?

**Comment by pmfx** [comment]
#14 It works great! Thanks Deesen.

**Comment by Deesen** [comment]
Great, then no need to answer your last question.
