### ISSUE TITLE
First click update tree-button, then click update elements-button causes "possible CSFR attempt"

### ISSUE THREAD

**Issue by Deesen** [pmfx/ElementsInTree#20]
Do you guys experience the same?

**Comment by pmfx** [comment]
Yes, I had to uncheck "Validate HTTP_REFERER headers?" in site configuration to get rid of it. Can we fix it somehow?

**Comment by Deesen** [comment]
Will try !

**Comment by Deesen** [comment]
Ok I think I found a solution. But I will also add the "lock icons" and maybe refactor the code as it looks quite dirty and "patchworked" now. So you can wait before new version release.

**Comment by pmfx** [comment]
Great news Deesen :) Is PR #21 ready to be merged and new release?

**Comment by pmfx** [comment]
@Deesen any updates on this?

**Comment by Deesen** [comment]
Still working as I tried to improve "lock elements"-function, like update lock-icons display in tree periodically. But I am unsure if it is really nessecary.

**Comment by pmfx** [comment]
Sounds itnteresting but do we really need it? Maybe not. Maybe a Welcome Screen Widget displaying currently locked documents would do the job?

**Comment by Deesen** [comment]
The job of displaying locks at init is already done, no problem. However, I was experimenting, that is the reason of delay.

**Comment by pmfx** [comment]
OK, let me know when to merge cause I don't know when dmi3yy gonna drop the 1.2-RC1 bomb :D
