### ISSUE TITLE
Idea: Context-Menu like Resource-tree with "Duplicate"-Button etc

### ISSUE THREAD

**Issue by Deesen** [pmfx/ElementsInTree#22]
:-)

**Comment by Deesen** [comment]
No hooray?

**Comment by pmfx** [comment]
Totally hooray!

**Comment by Deesen** [comment]
Like 

![context](https://cloud.githubusercontent.com/assets/8569221/20303075/103f7de8-ab2a-11e6-9247-d70e27f00a16.png)

**Comment by pmfx** [comment]
Yeah, that would be lovely.

**Comment by fourroses666** [comment]
Thats nice, although my Mac doesn't have the right click still its pritty cool.
