### ISSUE TITLE
Remember scroll position, tab-header position fix on top

### ISSUE THREAD

**Issue by Deesen** [pmfx/ElementsInTree#23]
When having a long lists of chunks and editing the last chunk in list, the frame jumps up because of being reloaded. I think 

- tabs and search-fields should be positioned fix on top
- "new element"-button and "reload"-button should be positioned beside search-field
- categories & elements should be wrapped in a DIV-container with `overflow-y:auto` instead of using frame-scrollbar. The DIVs max-height is frame-height so the frame´s scrollbar will be avoided
- scroll-position of this DIV will be saved and loaded on window-leave & -load to avoid issue mentioned at beginning

**Comment by pmfx** [comment]
I can work on "new element button and reload button should be positioned beside search-field". Text of "new element" will be replaced with icon (file or plus sign).

**Comment by Deesen** [comment]
Nice ok! And I also think the 10px margin is totally unnessecary, what do you think?

![margin](https://cloud.githubusercontent.com/assets/8569221/20302487/cbb11a8a-ab27-11e6-88f7-dfcaef3b6a7c.png)

**Comment by pmfx** [comment]
I think we should leave margin there.
Buttons next to search form are ready for testing :) https://github.com/pmfx/ElementsInTree/commit/b22592b6afd9ea436a38724d3718d5c2031fd68c

**Comment by pmfx** [comment]
Some visuals ;)

![screenshot_1](https://cloud.githubusercontent.com/assets/10888055/20323947/12553708-ab7f-11e6-8011-8df77666e48c.png)

**Comment by Deesen** [comment]
Looks good :+1: , thanks!

The "remember scroll" etc is also already working but still some issues to fix. I hope I will make it today.

**Comment by pmfx** [comment]
So all done here?

**Comment by Deesen** [comment]
I think so. Closing issue now.
