### ISSUE TITLE
Option to have categories collapsed or not by default

### ISSUE THREAD

**Issue by pmfx** [pmfx/ElementsInTree#3]
Create configuration option to have categories collapsed or not by default.

**Comment by Deesen** [comment]
Or maybe a remember-option? No problem with localStorage. And using shift-click on a category resulting in expanding/collapsing all categories?

**Comment by pmfx** [comment]
Yes, sounds even better!

**Comment by pmfx** [comment]
Closing this issue. Solved be @Deesen in https://github.com/pmfx/ElementsInTree/pull/7
