### ISSUE TITLE
Modules tab not using "User group access"

### ISSUE THREAD

**Issue by pmfx** [pmfx/ElementsInTree#5]
Modules tab shouldn't display all modules but only those that user is allowed to use (User group access).

**Comment by Nicola1971** [comment]
does not work with "_hasPermission_"? do you know how to solve it?

there is another small permission bug:  The "**new module**" button requires permission to create module instead run.

**Comment by pmfx** [comment]
Yes, I'm close to solving it. Copied part of code from /manager/frames/mainmenu.php:59 and it kind of works but instead of category name I get category ID. Some SQL syntax needed...

Will fix button too.

**Comment by pmfx** [comment]
@Nicola1971 I think I got it fixed now :) Can you test too?
Plus it uses system language in "new" buttons now.

**Comment by pmfx** [comment]
Still got some issues there but this time with collapsing / categories grouping.

**Comment by Nicola1971** [comment]
what kind of collapsing issues? no issue for me

**Comment by pmfx** [comment]
Fixed. Categories were displayed like two or three times if you had more modules in the same category.
